# Generated by Django 4.0.1 on 2022-02-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_pokemoncard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='moves',
            field=models.JSONField(default=['scratch', 'pay-day']),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='rarity',
            field=models.CharField(default='common', max_length=32),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='name',
            field=models.CharField(default='persian', max_length=32),
        ),
    ]
