# Generated by Django 4.0.1 on 2022-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_pokemoncard_moves_pokemoncard_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='moves',
            field=models.JSONField(default=['mega-punch', 'double-slap']),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='name',
            field=models.CharField(default='clefable', max_length=32),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='rarity',
            field=models.CharField(default='uncommon', max_length=32),
        ),
    ]
