# Generated by Django 4.0.1 on 2022-02-01 18:32

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_trainer_cards_delete_pokemoncard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cards',
            field=models.JSONField(default=[Users.models.create_card, Users.models.create_card]),
        ),
    ]
