# Generated by Django 4.0.1 on 2022-02-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_trainer_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cards',
            field=models.JSONField(default=[{'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'moves': {'base': {'class': 'physical', 'name': 'fire-punch', 'power': 75, 'type': 'fire'}, 'special': {'class': 'physical', 'name': 'mega-punch', 'power': 80, 'type': 'normal'}}, 'name': 'charmander', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'pokemon_int': 4, 'rarity': 'common', 'stats': {'attack': 52, 'defense': 43, 'hp': 39, 'special-attack': 60, 'special-defense': 50}, 'types': ['fire']}, {'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/94.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png', 'moves': {'base': {'class': 'physical', 'name': 'fire-punch', 'power': 75, 'type': 'fire'}, 'special': {'class': 'physical', 'name': 'mega-punch', 'power': 80, 'type': 'normal'}}, 'name': 'gengar', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'pokemon_int': 94, 'rarity': 'common', 'stats': {'attack': 65, 'defense': 60, 'hp': 60, 'special-attack': 130, 'special-defense': 75}, 'types': ['ghost', 'poison']}]),
        ),
    ]
