# Generated by Django 4.0.1 on 2022-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_trainer_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cards',
            field=models.JSONField(default=[{'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/88.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png', 'moves': {'base': {'class': 'physical', 'name': 'fire-punch', 'power': 75, 'type': 'fire'}, 'special': {'class': 'physical', 'name': 'pound', 'power': 40, 'type': 'normal'}}, 'name': 'grimer', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 'pokemon_int': 88, 'rarity': 'common', 'stats': {'attack': 80, 'defense': 50, 'hp': 80, 'special-attack': 40, 'special-defense': 50}, 'types': ['poison']}, {'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/98.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png', 'moves': {'base': {'class': 'physical', 'name': 'guillotine', 'power': None, 'type': 'normal'}, 'special': {'class': 'physical', 'name': 'vice-grip', 'power': 55, 'type': 'normal'}}, 'name': 'krabby', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 'pokemon_int': 98, 'rarity': 'uncommon', 'stats': {'attack': 115.50000000000001, 'defense': 99.00000000000001, 'hp': 33.0, 'special-attack': 27.500000000000004, 'special-defense': 27.500000000000004}, 'types': ['water']}]),
        ),
    ]
