# Generated by Django 4.0.1 on 2022-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_trainer_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cards',
            field=models.JSONField(default=[{'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/141.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png', 'moves': {'base': {'class': 'special', 'name': 'razor-wind', 'power': 80, 'type': 'normal'}, 'special': {'class': 'physical', 'name': 'scratch', 'power': 40, 'type': 'normal'}}, 'name': 'kabutops', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png', 'pokemon_int': 141, 'rarity': 'uncommon', 'stats': {'attack': 126.50000000000001, 'defense': 115.50000000000001, 'hp': 66.0, 'special-attack': 71.5, 'special-defense': 77.0}, 'types': ['rock', 'water']}, {'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/53.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png', 'moves': {'base': {'class': 'physical', 'name': 'scratch', 'power': 40, 'type': 'normal'}, 'special': {'class': 'physical', 'name': 'pay-day', 'power': 40, 'type': 'normal'}}, 'name': 'persian', 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 'pokemon_int': 53, 'rarity': 'uncommon', 'stats': {'attack': 77.0, 'defense': 66.0, 'hp': 71.5, 'special-attack': 71.5, 'special-defense': 71.5}, 'types': ['normal']}]),
        ),
    ]
