# Generated by Django 4.0.1 on 2022-02-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_trainer_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='cards',
            field=models.JSONField(default="[{'pokemon_int': 150, 'name': 'mewtwo', 'rarity': 'uncommon', 'types': ['psychic'], 'moves': {'base': {'name': 'pay-day', 'power': 63, 'class': 'physical', 'type': 'normal'}, 'special': {'name': 'mega-punch', 'power': 119, 'class': 'physical', 'type': 'normal'}}, 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png', 'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/150.png', 'stats': {'hp': 116.60000000000001, 'attack': 121.00000000000001, 'special-attack': 169.4, 'defense': 99.00000000000001, 'special-defense': 99.00000000000001}}, {'pokemon_int': 25, 'name': 'pikachu', 'rarity': 'uncommon', 'types': ['electric'], 'moves': {'base': {'name': 'pay-day', 'power': 63, 'class': 'physical', 'type': 'normal'}, 'special': {'name': 'mega-punch', 'power': 119, 'class': 'physical', 'type': 'normal'}}, 'official_artwork': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'front': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'back': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png', 'stats': {'hp': 38.5, 'attack': 60.50000000000001, 'special-attack': 55.00000000000001, 'defense': 44.0, 'special-defense': 55.00000000000001}}]"),
        ),
    ]
