# Generated by Django 4.0.1 on 2022-02-06 03:17

from django.db import migrations, models
import django.contrib


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_trainer_cards'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='trainer',
        name='cards',
    ),
    migrations.AddField(
        model_name='trainer',
        name='cards',
        field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
    ),
]
