# Generated by Django 4.0.1 on 2022-02-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_trainer_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='cards',
        ),
    ]
