# Generated by Django 4.0.1 on 2022-02-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_rename_cards_trainer_decks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='prev_battles',
        ),
    ]
