# Generated by Django 4.0.1 on 2022-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.AddField(
            model_name='game',
            name='current',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='deck1',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='deck2',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(default={'player1': None, 'player2': None}),
        ),
    ]
