# Generated by Django 4.0.1 on 2022-02-03 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Games', '0002_remove_game_player1_game_current_game_deck1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deck1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deck2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='active_comp_pokemon',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='active_player_pokemon',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='comp_pokemon',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='ghost',
            field=models.CharField(default='Computer', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_pokemon',
            field=models.JSONField(default=list),
        ),
    ]
