# Generated by Django 4.0.1 on 2022-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_remove_game_current_remove_game_deck1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comp_poke_status',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='user_poke_status',
            field=models.JSONField(default=list),
        ),
    ]
