# Generated by Django 4.0.1 on 2022-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_game_comp_poke_status_game_user_poke_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move',
            field=models.CharField(default='smack', max_length=16),
        ),
    ]
