# Generated by Django 4.0.1 on 2022-02-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_game_last_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='active_player_pokemon',
            new_name='active_user_pokemon',
        ),
    ]
