# Generated by Django 4.0.1 on 2022-02-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_rename_active_player_pokemon_game_active_user_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
